version: "3.3"

services:
  postgres:
    image: postgres:17.2
    environment:
      POSTGRES_USER: devices
      POSTGRES_PASSWORD: devices
      POSTGRES_DB: devices
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devices -d devices"]
      interval: 2s
      timeout: 10s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://devices:devices@postgres:5432/devices?sslmode=disable",
      "up"
    ]
