// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID        int32              `db:"id" json:"id"`
	Name      pgtype.Text        `db:"name" json:"name"`
	Brand     pgtype.Text        `db:"brand" json:"brand"`
	State     string             `db:"state" json:"state"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
