// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package queries

import (
	"context"
)

const getDevice = `-- name: GetDevice :one
SELECT id, name, brand, state, created_at FROM devices WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, db DBTX, id int32) (*Device, error) {
	row := db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.State,
		&i.CreatedAt,
	)
	return &i, err
}
